IF
	Global("JA#ELFSONG_QUEST","GLOBAL",7)
	Global("JA#ELVENLADY_SPWN","%EBaldursGate_ElfsongTavern_L2%",0)
	PartyHasItem("JA#HRP01")
THEN
	RESPONSE #100
		SetGlobal("JA#ELVENLADY_SPWN","%EBaldursGate_ElfsongTavern_L2%",1)
		CreateCreature("JA#ESELY",[645.161],14)
		Continue()
END

IF
	Global("JA#ELFSONG_QUEST","GLOBAL",9)
	GlobalTimerExpired("JA#HARP_TIMER","%EBaldursGate_ElfsongTavern_L2%")
THEN
	RESPONSE #100
		SetGlobal("JA#ELFSONG_QUEST","GLOBAL",10)
		Continue()
END
