IF
	Global("Doppleganger","GLOBAL",1)
	Global("JA#LEAVE_AREA","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("JA#LEAVE_AREA","LOCALS",1)
		SmallWait(5)
		DisplayStringHead(Myself,46151) // Hilfe!
		EscapeArea()
END

IF
	Global("ScarMission","GLOBAL",1)
	See([PC])
	NumberOfTimesTalkedTo(0)
	Global("JA#SSMER_DLG","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("JA#SSMER_DLG","GLOBAL",1)
		Dialogue([PC])
END
