IF
	See([PC])
	StateCheck("SSDopple", STATE_DEAD)
	!See([ENEMY])
	Global("JA#DLG_GUA","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("JA#DLG_GUA","LOCALS",1)
		Dialogue([PC])
END

IF
	!Allegiance(Myself,ENEMY)
	See([ENEMY])
	Class(LastSeenBy(Myself),DOPPLEGANGER)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate([ENEMY],30)
END

IF
	Range([PC],5)
	See([PC])
	NumberOfTimesTalkedTo(0)
	Allegiance(Myself,NEUTRAL)
	CombatCounter(0)
THEN
	RESPONSE #100
		StartDialogueNoSet([PC])
END
