IF
	OnCreation()
	!GlobalTimerNotExpired("JA#DEADCOCK","GLOBAL")
	!Exists("JA#COCK1")
THEN
	RESPONSE #100
		SetGlobal("JA#BRAUN_TOT","%NashkelCarnival%",0)
		CreateCreature("JA#COCK1",[2586.3399],12)
		Continue()
END

IF
	OnCreation()
	!GlobalTimerNotExpired("JA#DEADCOCK","GLOBAL")
	!Exists("JA#COCK2")
THEN
	RESPONSE #100
		SetGlobal("JA#WEISS_TOT","%NashkelCarnival%",0)
		CreateCreature("JA#COCK2",[2640.3405],5)
		Continue()
END
