IF
	See([PC])
	Global("JA#VOLT_SPWN","%NWBaldursGate_LaertasHouse_L1%",52)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		SetGlobal("JA#VOLT_SPWN","%NWBaldursGate_LaertasHouse_L1%",53)
		Wait(3)
		StartDialogueNoSet([PC])
END

IF
    See(NearestEnemyOf(Myself))
	Global("JA#VOLT_FIGHT","GLOBAL",0)
THEN
    RESPONSE #100
		SetGlobal("JA#VOLT_FIGHT","GLOBAL",1)
        ReallyForceSpell(Myself,CLERIC_BARKSKIN)
		SmallWait(1)
        ForceSpell(NearestEnemyOf(Myself),CLERIC_SUMMON_INSECTS)
END
